// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerformanceApp.Server.Data;

#nullable disable

namespace PerformanceApp.Server.Migrations
{
    [DbContext(typeof(PadbContext))]
    [Migration("20251112071517_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.Benchmark", b =>
                {
                    b.Property<int>("PortfolioId")
                        .HasColumnType("int")
                        .HasColumnName("PortfolioID");

                    b.Property<int>("BenchmarkId")
                        .HasColumnType("int")
                        .HasColumnName("BenchmarkID");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("PortfolioId", "BenchmarkId");

                    b.HasIndex("BenchmarkId");

                    b.ToTable("Benchmark", "padb");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.DateInfo", b =>
                {
                    b.Property<DateOnly>("Bankday")
                        .HasColumnType("date");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Bankday");

                    b.ToTable("DateInfo", "padb");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.Instrument", b =>
                {
                    b.Property<int>("InstrumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InstrumentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstrumentId"));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("InstrumentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("InstrumentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("InstrumentTypeID");

                    b.HasKey("InstrumentId");

                    b.HasIndex("InstrumentTypeId");

                    b.HasIndex(new[] { "InstrumentName" }, "UQ_Instrument_InstrumentName")
                        .IsUnique()
                        .HasFilter("[InstrumentName] IS NOT NULL");

                    b.ToTable("Instrument", "padb");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.InstrumentDayPerformance", b =>
                {
                    b.Property<int>("InstrumentId")
                        .HasColumnType("int")
                        .HasColumnName("InstrumentID");

                    b.Property<DateOnly>("Bankday")
                        .HasColumnType("date");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("DayPerformance")
                        .HasColumnType("decimal(24, 16)");

                    b.HasKey("InstrumentId", "Bankday");

                    b.HasIndex("Bankday");

                    b.ToTable("InstrumentDayPerformance", "padb");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.InstrumentHalfYearPerformance", b =>
                {
                    b.Property<int>("InstrumentId")
                        .HasColumnType("int")
                        .HasColumnName("InstrumentID");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("HalfYearPerformance")
                        .HasColumnType("decimal(24, 16)");

                    b.HasKey("InstrumentId", "PeriodStart", "PeriodEnd");

                    b.HasIndex("PeriodEnd");

                    b.HasIndex("PeriodStart");

                    b.ToTable("InstrumentHalfYearPerformance", "padb");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.InstrumentMonthPerformance", b =>
                {
                    b.Property<int>("InstrumentId")
                        .HasColumnType("int")
                        .HasColumnName("InstrumentID");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("MonthPerformance")
                        .HasColumnType("decimal(24, 16)");

                    b.HasKey("InstrumentId", "PeriodStart", "PeriodEnd");

                    b.HasIndex("PeriodEnd");

                    b.HasIndex("PeriodStart");

                    b.ToTable("InstrumentMonthPerformance", "padb");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.InstrumentPrice", b =>
                {
                    b.Property<int>("InstrumentId")
                        .HasColumnType("int")
                        .HasColumnName("InstrumentID");

                    b.Property<DateOnly>("Bankday")
                        .HasColumnType("date");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(19, 4)");

                    b.HasKey("InstrumentId", "Bankday");

                    b.HasIndex("Bankday");

                    b.ToTable("InstrumentPrice", "padb");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.InstrumentType", b =>
                {
                    b.Property<int>("InstrumentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InstrumentTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstrumentTypeId"));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("InstrumentTypeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("InstrumentTypeId");

                    b.ToTable("InstrumentType", "padb");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.KeyFigureInfo", b =>
                {
                    b.Property<int>("KeyFigureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KeyFigureID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KeyFigureId"));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("KeyFigureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("KeyFigureId");

                    b.HasIndex(new[] { "KeyFigureName" }, "UQ_KeyFigureInfo_KeyFigureName")
                        .IsUnique();

                    b.ToTable("KeyFigureInfo", "padb");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.KeyFigureValue", b =>
                {
                    b.Property<int>("PortfolioId")
                        .HasColumnType("int")
                        .HasColumnName("PortfolioID");

                    b.Property<int>("KeyFigureId")
                        .HasColumnType("int")
                        .HasColumnName("KeyFigureID");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("KeyFigureValue1")
                        .HasColumnType("decimal(24, 16)")
                        .HasColumnName("KeyFigureValue");

                    b.HasKey("PortfolioId", "KeyFigureId");

                    b.HasIndex("KeyFigureId");

                    b.ToTable("KeyFigureValue", "padb");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.Portfolio", b =>
                {
                    b.Property<int>("PortfolioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PortfolioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PortfolioId"));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PortfolioName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PortfolioId");

                    b.HasIndex("UserID");

                    b.HasIndex(new[] { "PortfolioName" }, "UQ_Portfolio_PortfolioName")
                        .IsUnique();

                    b.ToTable("Portfolio", "padb");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.PortfolioCumulativeDayPerformance", b =>
                {
                    b.Property<int>("PortfolioId")
                        .HasColumnType("int")
                        .HasColumnName("PortfolioID");

                    b.Property<DateOnly>("Bankday")
                        .HasColumnType("date");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("CumulativeDayPerformance")
                        .HasColumnType("decimal(24, 16)");

                    b.HasKey("PortfolioId", "Bankday");

                    b.HasIndex("Bankday");

                    b.ToTable("PortfolioCumulativeDayPerformance", "padb");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.PortfolioDayPerformance", b =>
                {
                    b.Property<int>("PortfolioId")
                        .HasColumnType("int")
                        .HasColumnName("PortfolioID");

                    b.Property<DateOnly>("Bankday")
                        .HasColumnType("date");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("DayPerformance")
                        .HasColumnType("decimal(24, 16)");

                    b.HasKey("PortfolioId", "Bankday");

                    b.HasIndex("Bankday");

                    b.ToTable("PortfolioDayPerformance", "padb");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.PortfolioHalfYearPerformance", b =>
                {
                    b.Property<int>("PortfolioId")
                        .HasColumnType("int")
                        .HasColumnName("PortfolioID");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("HalfYearPerformance")
                        .HasColumnType("decimal(24, 16)");

                    b.HasKey("PortfolioId", "PeriodStart", "PeriodEnd");

                    b.HasIndex("PeriodEnd");

                    b.HasIndex("PeriodStart");

                    b.ToTable("PortfolioHalfYearPerformance", "padb");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.PortfolioMonthPerformance", b =>
                {
                    b.Property<int>("PortfolioId")
                        .HasColumnType("int")
                        .HasColumnName("PortfolioID");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("MonthPerformance")
                        .HasColumnType("decimal(24, 16)");

                    b.HasKey("PortfolioId", "PeriodStart", "PeriodEnd");

                    b.HasIndex("PeriodEnd");

                    b.HasIndex("PeriodStart");

                    b.ToTable("PortfolioMonthPerformance", "padb");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.PortfolioValue", b =>
                {
                    b.Property<int>("PortfolioId")
                        .HasColumnType("int")
                        .HasColumnName("PortfolioID");

                    b.Property<DateOnly>("Bankday")
                        .HasColumnType("date");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("PortfolioValue1")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("PortfolioValue");

                    b.HasKey("PortfolioId", "Bankday");

                    b.HasIndex("Bankday");

                    b.ToTable("PortfolioValue", "padb");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PositionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(19, 4)");

                    b.Property<DateOnly?>("Bankday")
                        .HasColumnType("date");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("InstrumentId")
                        .HasColumnType("int")
                        .HasColumnName("InstrumentID");

                    b.Property<decimal?>("Nominal")
                        .HasColumnType("decimal(19, 4)");

                    b.Property<int?>("PortfolioId")
                        .HasColumnType("int")
                        .HasColumnName("PortfolioID");

                    b.Property<decimal?>("Proportion")
                        .HasColumnType("decimal(5, 4)");

                    b.HasKey("PositionId");

                    b.HasIndex("Bankday");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Position", "padb");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.PositionValue", b =>
                {
                    b.Property<int>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("PositionID");

                    b.Property<DateOnly>("Bankday")
                        .HasColumnType("date");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("PositionValue1")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("PositionValue");

                    b.HasKey("PositionId", "Bankday");

                    b.HasIndex("Bankday");

                    b.ToTable("PositionValue", "padb");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.Staging", b =>
                {
                    b.Property<DateOnly?>("Bankday")
                        .HasColumnType("date");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("InstrumentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InstrumentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(19, 4)");

                    b.ToTable("Staging", "padb");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransactionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(19, 4)");

                    b.Property<DateOnly?>("Bankday")
                        .HasColumnType("date");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("InstrumentId")
                        .HasColumnType("int")
                        .HasColumnName("InstrumentID");

                    b.Property<decimal?>("Nominal")
                        .HasColumnType("decimal(19, 4)");

                    b.Property<int?>("PortfolioId")
                        .HasColumnType("int")
                        .HasColumnName("PortfolioID");

                    b.Property<decimal?>("Proportion")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<int?>("TransactionTypeId")
                        .HasColumnType("int")
                        .HasColumnName("TransactionTypeID");

                    b.HasKey("TransactionId");

                    b.HasIndex("Bankday");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("Transaction", "padb");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.TransactionType", b =>
                {
                    b.Property<int>("TransactionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransactionTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionTypeId"));

                    b.Property<string>("TransactionTypeName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TransactionTypeId");

                    b.HasIndex(new[] { "TransactionTypeName" }, "UQ_TransactionType_TransactionTypeName")
                        .IsUnique()
                        .HasFilter("[TransactionTypeName] IS NOT NULL");

                    b.ToTable("TransactionType", "padb");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("PerformanceApp.Server.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PerformanceApp.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PerformanceApp.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("PerformanceApp.Server.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PerformanceApp.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PerformanceApp.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.Benchmark", b =>
                {
                    b.HasOne("PerformanceApp.Server.Models.Portfolio", "BenchmarkPortfolioNavigation")
                        .WithMany("BenchmarkBenchmarksNavigation")
                        .HasForeignKey("BenchmarkId")
                        .IsRequired()
                        .HasConstraintName("FK_Benchmark_BenchmarkID");

                    b.HasOne("PerformanceApp.Server.Models.Portfolio", "PortfolioPortfolioNavigation")
                        .WithMany("BenchmarkPortfoliosNavigation")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Benchmark_PortfolioID");

                    b.Navigation("BenchmarkPortfolioNavigation");

                    b.Navigation("PortfolioPortfolioNavigation");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.Instrument", b =>
                {
                    b.HasOne("PerformanceApp.Server.Models.InstrumentType", "InstrumentTypeNavigation")
                        .WithMany("InstrumentsNavigation")
                        .HasForeignKey("InstrumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Instrument_InstrumentTypeID");

                    b.Navigation("InstrumentTypeNavigation");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.InstrumentDayPerformance", b =>
                {
                    b.HasOne("PerformanceApp.Server.Models.DateInfo", "BankdayNavigation")
                        .WithMany("InstrumentDayPerformancesNavigation")
                        .HasForeignKey("Bankday")
                        .IsRequired()
                        .HasConstraintName("FK_InstrumentDayPerformance_Bankday");

                    b.HasOne("PerformanceApp.Server.Models.Instrument", "InstrumentNavigation")
                        .WithMany("InstrumentDayPerformancesNavigation")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InstrumentDayPerformance_InstrumentID");

                    b.Navigation("BankdayNavigation");

                    b.Navigation("InstrumentNavigation");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.InstrumentHalfYearPerformance", b =>
                {
                    b.HasOne("PerformanceApp.Server.Models.Instrument", "InstrumentNavigation")
                        .WithMany("InstrumentHalfYearPerformancesNavigation")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InstrumentHalfYearPerformance_InstrumentID");

                    b.HasOne("PerformanceApp.Server.Models.DateInfo", "PeriodEndNavigation")
                        .WithMany("InstrumentHalfYearPerformancePeriodEndsNavigation")
                        .HasForeignKey("PeriodEnd")
                        .IsRequired()
                        .HasConstraintName("FK_InstrumentHalfYearPerformance_PeriodEnd");

                    b.HasOne("PerformanceApp.Server.Models.DateInfo", "PeriodStartNavigation")
                        .WithMany("InstrumentHalfYearPerformancePeriodStartsNavigation")
                        .HasForeignKey("PeriodStart")
                        .IsRequired()
                        .HasConstraintName("FK_InstrumentHalfYearPerformance_PeriodStart");

                    b.Navigation("InstrumentNavigation");

                    b.Navigation("PeriodEndNavigation");

                    b.Navigation("PeriodStartNavigation");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.InstrumentMonthPerformance", b =>
                {
                    b.HasOne("PerformanceApp.Server.Models.Instrument", "InstrumentNavigation")
                        .WithMany("InstrumentMonthPerformancesNavigation")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InstrumentMonthPerformance_InstrumentID");

                    b.HasOne("PerformanceApp.Server.Models.DateInfo", "PeriodEndNavigation")
                        .WithMany("InstrumentMonthPerformancePeriodEndsNavigation")
                        .HasForeignKey("PeriodEnd")
                        .IsRequired()
                        .HasConstraintName("FK_InstrumentMonthPerformance_PeriodEnd");

                    b.HasOne("PerformanceApp.Server.Models.DateInfo", "PeriodStartNavigation")
                        .WithMany("InstrumentMonthPerformancePeriodStartsNavigation")
                        .HasForeignKey("PeriodStart")
                        .IsRequired()
                        .HasConstraintName("FK_InstrumentMonthPerformance_PeriodStart");

                    b.Navigation("InstrumentNavigation");

                    b.Navigation("PeriodEndNavigation");

                    b.Navigation("PeriodStartNavigation");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.InstrumentPrice", b =>
                {
                    b.HasOne("PerformanceApp.Server.Models.DateInfo", "BankdayNavigation")
                        .WithMany("InstrumentPricesNavigation")
                        .HasForeignKey("Bankday")
                        .IsRequired()
                        .HasConstraintName("FK_InstrumentPrice_Bankday");

                    b.HasOne("PerformanceApp.Server.Models.Instrument", "InstrumentNavigation")
                        .WithMany("InstrumentPricesNavigation")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InstrumentPrice_InstrumentID");

                    b.Navigation("BankdayNavigation");

                    b.Navigation("InstrumentNavigation");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.KeyFigureValue", b =>
                {
                    b.HasOne("PerformanceApp.Server.Models.KeyFigureInfo", "KeyFigureInfoNavigation")
                        .WithMany("KeyFigureValuesNavigation")
                        .HasForeignKey("KeyFigureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KeyFigureValue_KeyFigureID");

                    b.HasOne("PerformanceApp.Server.Models.Portfolio", "PortfolioNavigation")
                        .WithMany("KeyFigureValuesNavigation")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KeyFigureValue_PortfolioID");

                    b.Navigation("KeyFigureInfoNavigation");

                    b.Navigation("PortfolioNavigation");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.Portfolio", b =>
                {
                    b.HasOne("PerformanceApp.Server.Models.ApplicationUser", "User")
                        .WithMany("PortfoliosNavigation")
                        .HasForeignKey("UserID")
                        .HasConstraintName("FK_Portfolio_UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.PortfolioCumulativeDayPerformance", b =>
                {
                    b.HasOne("PerformanceApp.Server.Models.DateInfo", "BankdayNavigation")
                        .WithMany("PortfolioCumulativeDayPerformancesNavigation")
                        .HasForeignKey("Bankday")
                        .IsRequired()
                        .HasConstraintName("FK_PortfolioCumulativeDayPerformance_Bankday");

                    b.HasOne("PerformanceApp.Server.Models.Portfolio", "PortfolioNavigation")
                        .WithMany("PortfolioCumulativeDayPerformancesNavigation")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PortfolioCumulativeDayPerformance_PortfolioID");

                    b.Navigation("BankdayNavigation");

                    b.Navigation("PortfolioNavigation");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.PortfolioDayPerformance", b =>
                {
                    b.HasOne("PerformanceApp.Server.Models.DateInfo", "BankdayNavigation")
                        .WithMany("PortfolioDayPerformancesNavigation")
                        .HasForeignKey("Bankday")
                        .IsRequired()
                        .HasConstraintName("FK_PortfolioDayPerformance_Bankday");

                    b.HasOne("PerformanceApp.Server.Models.Portfolio", "PortfolioNavigation")
                        .WithMany("PortfolioDayPerformancesNavigation")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PortfolioDayPerformance_PortfolioID");

                    b.Navigation("BankdayNavigation");

                    b.Navigation("PortfolioNavigation");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.PortfolioHalfYearPerformance", b =>
                {
                    b.HasOne("PerformanceApp.Server.Models.DateInfo", "PeriodEndNavigation")
                        .WithMany("PortfolioHalfYearPerformancePeriodEndsNavigation")
                        .HasForeignKey("PeriodEnd")
                        .IsRequired()
                        .HasConstraintName("FK_PortfolioHalfYearPerformance_PeriodEnd");

                    b.HasOne("PerformanceApp.Server.Models.DateInfo", "PeriodStartNavigation")
                        .WithMany("PortfolioHalfYearPerformancePeriodStartsNavigation")
                        .HasForeignKey("PeriodStart")
                        .IsRequired()
                        .HasConstraintName("FK_PortfolioHalfYearPerformance_PeriodStart");

                    b.HasOne("PerformanceApp.Server.Models.Portfolio", "PortfolioNavigation")
                        .WithMany("PortfolioHalfYearPerformancesNavigation")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PortfolioHalfYearPerformance_PortfolioID");

                    b.Navigation("PeriodEndNavigation");

                    b.Navigation("PeriodStartNavigation");

                    b.Navigation("PortfolioNavigation");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.PortfolioMonthPerformance", b =>
                {
                    b.HasOne("PerformanceApp.Server.Models.DateInfo", "PeriodEndNavigation")
                        .WithMany("PortfolioMonthPerformancePeriodEndsNavigation")
                        .HasForeignKey("PeriodEnd")
                        .IsRequired()
                        .HasConstraintName("FK_PortfolioMonthPerformance_PeriodEnd");

                    b.HasOne("PerformanceApp.Server.Models.DateInfo", "PeriodStartNavigation")
                        .WithMany("PortfolioMonthPerformancePeriodStartsNavigation")
                        .HasForeignKey("PeriodStart")
                        .IsRequired()
                        .HasConstraintName("FK_PortfolioMonthPerformance_PeriodStart");

                    b.HasOne("PerformanceApp.Server.Models.Portfolio", "PortfolioNavigation")
                        .WithMany("PortfolioMonthPerformancesNavigation")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PortfolioMonthPerformance_PortfolioID");

                    b.Navigation("PeriodEndNavigation");

                    b.Navigation("PeriodStartNavigation");

                    b.Navigation("PortfolioNavigation");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.PortfolioValue", b =>
                {
                    b.HasOne("PerformanceApp.Server.Models.DateInfo", "BankdayNavigation")
                        .WithMany("PortfolioValuesNavigation")
                        .HasForeignKey("Bankday")
                        .IsRequired()
                        .HasConstraintName("FK_PortfolioValue_Bankday");

                    b.HasOne("PerformanceApp.Server.Models.Portfolio", "PortfolioNavigation")
                        .WithMany("PortfolioValuesNavigation")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PortfolioValue_PortfolioID");

                    b.Navigation("BankdayNavigation");

                    b.Navigation("PortfolioNavigation");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.Position", b =>
                {
                    b.HasOne("PerformanceApp.Server.Models.DateInfo", "BankdayNavigation")
                        .WithMany("PositionsNavigation")
                        .HasForeignKey("Bankday")
                        .HasConstraintName("FK_Position_Bankday");

                    b.HasOne("PerformanceApp.Server.Models.Instrument", "InstrumentNavigation")
                        .WithMany("PositionsNavigation")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Position_InstrumentID");

                    b.HasOne("PerformanceApp.Server.Models.Portfolio", "PortfolioNavigation")
                        .WithMany("PositionsNavigation")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Position_PortfolioID");

                    b.Navigation("BankdayNavigation");

                    b.Navigation("InstrumentNavigation");

                    b.Navigation("PortfolioNavigation");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.PositionValue", b =>
                {
                    b.HasOne("PerformanceApp.Server.Models.DateInfo", "BankdayNavigation")
                        .WithMany("PositionValuesNavigation")
                        .HasForeignKey("Bankday")
                        .IsRequired()
                        .HasConstraintName("FK_PositionValue_Bankday");

                    b.HasOne("PerformanceApp.Server.Models.Position", "PositionNavigation")
                        .WithMany("PositionValuesNavigation")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PositionValue_PositionID");

                    b.Navigation("BankdayNavigation");

                    b.Navigation("PositionNavigation");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.Transaction", b =>
                {
                    b.HasOne("PerformanceApp.Server.Models.DateInfo", "BankdayNavigation")
                        .WithMany("TransactionsNavigation")
                        .HasForeignKey("Bankday")
                        .HasConstraintName("FK_Transaction_Bankday");

                    b.HasOne("PerformanceApp.Server.Models.Instrument", "InstrumentNavigation")
                        .WithMany("TransactionsNavigation")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Transaction_InstrumentID");

                    b.HasOne("PerformanceApp.Server.Models.Portfolio", "PortfolioNavigation")
                        .WithMany("TransactionsNavigation")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Transaction_PortfolioID");

                    b.HasOne("PerformanceApp.Server.Models.TransactionType", "TransactionTypeNavigation")
                        .WithMany("TransactionsNavigation")
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Transaction_TransactionTypeID");

                    b.Navigation("BankdayNavigation");

                    b.Navigation("InstrumentNavigation");

                    b.Navigation("PortfolioNavigation");

                    b.Navigation("TransactionTypeNavigation");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.ApplicationUser", b =>
                {
                    b.Navigation("PortfoliosNavigation");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.DateInfo", b =>
                {
                    b.Navigation("InstrumentDayPerformancesNavigation");

                    b.Navigation("InstrumentHalfYearPerformancePeriodEndsNavigation");

                    b.Navigation("InstrumentHalfYearPerformancePeriodStartsNavigation");

                    b.Navigation("InstrumentMonthPerformancePeriodEndsNavigation");

                    b.Navigation("InstrumentMonthPerformancePeriodStartsNavigation");

                    b.Navigation("InstrumentPricesNavigation");

                    b.Navigation("PortfolioCumulativeDayPerformancesNavigation");

                    b.Navigation("PortfolioDayPerformancesNavigation");

                    b.Navigation("PortfolioHalfYearPerformancePeriodEndsNavigation");

                    b.Navigation("PortfolioHalfYearPerformancePeriodStartsNavigation");

                    b.Navigation("PortfolioMonthPerformancePeriodEndsNavigation");

                    b.Navigation("PortfolioMonthPerformancePeriodStartsNavigation");

                    b.Navigation("PortfolioValuesNavigation");

                    b.Navigation("PositionValuesNavigation");

                    b.Navigation("PositionsNavigation");

                    b.Navigation("TransactionsNavigation");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.Instrument", b =>
                {
                    b.Navigation("InstrumentDayPerformancesNavigation");

                    b.Navigation("InstrumentHalfYearPerformancesNavigation");

                    b.Navigation("InstrumentMonthPerformancesNavigation");

                    b.Navigation("InstrumentPricesNavigation");

                    b.Navigation("PositionsNavigation");

                    b.Navigation("TransactionsNavigation");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.InstrumentType", b =>
                {
                    b.Navigation("InstrumentsNavigation");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.KeyFigureInfo", b =>
                {
                    b.Navigation("KeyFigureValuesNavigation");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.Portfolio", b =>
                {
                    b.Navigation("BenchmarkBenchmarksNavigation");

                    b.Navigation("BenchmarkPortfoliosNavigation");

                    b.Navigation("KeyFigureValuesNavigation");

                    b.Navigation("PortfolioCumulativeDayPerformancesNavigation");

                    b.Navigation("PortfolioDayPerformancesNavigation");

                    b.Navigation("PortfolioHalfYearPerformancesNavigation");

                    b.Navigation("PortfolioMonthPerformancesNavigation");

                    b.Navigation("PortfolioValuesNavigation");

                    b.Navigation("PositionsNavigation");

                    b.Navigation("TransactionsNavigation");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.Position", b =>
                {
                    b.Navigation("PositionValuesNavigation");
                });

            modelBuilder.Entity("PerformanceApp.Server.Models.TransactionType", b =>
                {
                    b.Navigation("TransactionsNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
